# Generated by Django 4.1.1 on 2022-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('Genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('literary', 'Literary'), ('non-fiction', 'Non-Fiction')], default='Fantasy', max_length=20)),
                ('Favorite', models.BooleanField(default=False)),
                ('Review', models.FloatField()),
            ],
        ),
    ]
